### ISSUE TITLE
Locale URL. Prefix lang to nice url's

### ISSUE THREAD

**Issue by raimonesteve** [openlabs/trytond-nereid#12]
Tryton url with locale is:
domain.com/es_ES/

Nice url and more usefull is:
domain.com/es/

We added a new field in ir.lang and separated currency and lang models: https://github.com/zikzakmedia/trytond-nereid/commit/3ced9630eb0a5020f19700daf5968304052a5850

Removed required attribute: https://github.com/zikzakmedia/trytond-nereid/commit/0a11b7905eba3c57f8368ee50397e1fc818940e0

**Comment by zikzakmedia** [comment]
See https://github.com/openlabs/nereid/issues/65 issue
