### ISSUE TITLE
Locale es_ES

### ISSUE THREAD

**Issue by ghost** [openlabs/trytond-nereid#13]
I published locale es_ES in locale branch from https://github.com/zikzakmedia/trytond-nereid

Locale. es_ES: https://github.com/zikzakmedia/trytond-nereid/commit/7f5dc60f307cb30de5f60c1d70bf6200e2ce10a3
i18n. es: https://github.com/zikzakmedia/trytond-nereid/commit/6d8c9df2fd0c6ea62783528b016a940772e7a4a7
i18n. es_ES: https://github.com/zikzakmedia/trytond-nereid/commit/2e15deed4afd27cf859ac26eb8d2120ad85c95ee

Remember update messages.pot file: https://github.com/zikzakmedia/trytond-nereid/commit/364b18bb4426961862e9d5b9fdd39d1e1338931b

**Comment by sharoonthomas** [comment]
you could send us pull requests directly ?

**Comment by zikzakmedia** [comment]
See https://github.com/openlabs/trytond-nereid/pull/15 pull request
