### ISSUE TITLE
Locale ca_ES

### ISSUE THREAD

**Issue by ghost** [openlabs/trytond-nereid#14]
I published locale ca_ES in locale branch from https://github.com/zikzakmedia/trytond-nereid

Locale. ca_ES: https://github.com/zikzakmedia/trytond-nereid/commit/a3a9f0893300a1d16aaf7e1baba71d71d22de5ca
i18n. ca: https://github.com/zikzakmedia/trytond-nereid/commit/53d4485e0fd19f18f7931447cc24d904cf66a0ed
i18n. ca_ES: https://github.com/zikzakmedia/trytond-nereid/commit/fad1cc19706035519fcb08cf6990f1d75ae7d150

Remember update messages.pot file: https://github.com/zikzakmedia/trytond-nereid/commit/364b18bb4426961862e9d5b9fdd39d1e1338931b

**Comment by zikzakmedia** [comment]
See https://github.com/openlabs/trytond-nereid/pull/15 pull request
